### ISSUE TITLE
missing username and password input

### ISSUE THREAD

**Issue by shahzadbacha** [ngageoint/elasticgeo#100]
Hi,
elasticgeo won't show option for putting username and password.
> ![image](https://user-images.githubusercontent.com/16791779/53559068-26ccb480-3b6b-11e9-83b0-64d55dfcc582.png)

**Note:** I am running Geoserver version 2.13.2 on CentOS 7

**Comment by sjudeng** [comment]
The update to add username/password support was in master but hadn't been included in a release yet. Please try again with the new [2.14.2-RC1](https://github.com/ngageoint/elasticgeo/releases/tag/2.14.2-RC1) release.

**Comment by shahzadbacha** [comment]
Thank you. That worked
