### ISSUE TITLE
Support for ElasticSearch 7.0

### ISSUE THREAD

**Issue by johndeereguy** [ngageoint/elasticgeo#104]
We are looking to upgrade to ElasticSearch 7.0, I just wanted to know when elasticgeo may be upgraded to support ES 7.0?  Has any investigation been done to see if the newest version of elasticgeo, 2.14.2-RC1, would work with ES 7.0?  Thank you!

**Comment by sjudeng** [comment]
We haven't started looking at updates to support Elasticsearch 7 yet but it is planned
