### ISSUE TITLE
[Question] Native query using terms filter

### ISSUE THREAD

**Issue by syncush** [ngageoint/elasticgeo#107]
GeoServer version: v2.15.2
elasticgeo version: v2.15.1-RC1
Elasticsearch version: v6.4.2

I would like to pass a native query to my elasticsearch that uses the terms filter,
I have tried the following

my query is : 
```
const query = {"terms":{"source": ["1", "2"]}}
const queryString = 'q:' + JSON.stringify(query).replace(',', '\\,');
https://mygeoserver.com/geoserver/workspace/wms?........&viewparams=${encodeURI(queryString)}
```
I have used encodeURI because without it I recieve an error indicating there are invalid characters in my queryString.

The error I receive is the following 

```
<ServiceException code="org.geoserver.wms.map.GetMapKvpRequestReader">
1 layers requested, but found 2 view params specified
</ServiceException>
```

Is the error I am receiving is related to directly to elasticgeo? is it possible to use the terms filter in native query?

**Comment by sjudeng** [comment]
See if it works to encode just the query body:

```javascript
const queryString = JSON.stringify(query).replace(',', '\\,');
const url = `https://mygeoserver.com/geoserver/workspace/wms?........&viewparams=q:${encodeURI(queryString)}`
```

**Comment by syncush** [comment]
Hi @sjudeng thank you for your answer but unfortunately, I still get the same error.

**Comment by syncush** [comment]
I fixed it, I just changed the encodeURI function to encodeURIComponent.

```
const query = {"terms":{"source": ["1", "2"]}}
const queryString = 'q:' + JSON.stringify(query).replace(',', '\\,');
https://mygeoserver.com/geoserver/workspace/wms?........&viewparams=${encodeURIComponent(queryString)}
```

Issue can be closed.

**Comment by sjudeng** [comment]
Great thank you for reporting back
