### ISSUE TITLE
Uncompatible with ElasticSearch 2.0

### ISSUE THREAD

**Issue by twozeroseven** [ngageoint/elasticgeo#17]
Attempting to connect from Geoserver 2.8.3 to ElasticSearch 2.0 and receiving the following error:
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []

**Comment by sjudeng** [comment]
Can you retry with a more recent Elasticsearch than 2.0? The plugin is compatible with Elasticsearch 2.1.x and 2.2.x. Make sure to download binaries that match your version of GeoServer and Elasticsearch or build from source.
