### ISSUE TITLE
Geo-point value precision

### ISSUE THREAD

**Issue by ericsvendsen-mil** [ngageoint/elasticgeo#19]
It seems that if there are geo-point values present in the Elasticsearch index that are integers (e.g. no decimals), then the feature won't show up in Geoserver. I don't know if this is a known issue, or if there's some configuration setting that we missed, but we had to manually add `.0` in order to see the data:

```
{
  "location": {
    "lat": 40.0,
    "lon": -95.0
  }
}
```

**Comment by sjudeng** [comment]
Thanks for the bug report. I don't think I ever tested geo_points with integer coordinates.
