### ISSUE TITLE
Installation into GeoServer Failed

### ISSUE THREAD

**Issue by giaconiamark** [ngageoint/elasticgeo#2]
Hello, I pulled down the code and built everything no problem via maven install...
Then I was not sure which jars to put in the lib dir of geoserver, so I put this jar in there
gs-web-elasticsearch-2.7-SNAPSHOT.jar. The docs say to put "the plugin" in the lib dir but I'm not sure what "the plugin" is.
Before I post all the exceptions in the Goeserver logs, I thought I would first ask if I am putting the right jars in the right place.

here's my geoserver specs
Version
2.7.0
Git Revision
b7cdbf9bbef0c5f88a3d30e132146ac9fa368b4b
Build Date
20-Mar-2015 19:44
GeoTools Version
13.0 (rev 3e400364d95c06a3e449c34dbc3c587a12bbdfb6)
GeoWebCache Version
1.7.0 (rev 1.7.x/c87a6d54381fd571424095702a43a6fd403e5148)

**Comment by giaconiamark** [comment]
so i made the plugin appear in GeoServer admin web ui... I got this to work by putting all the jars that are produced by both modules under the parent, in to the META-INF/lib dir.
Now I cannot get the "add store" to save my ES connection properties. Still working through it.

**Comment by giaconiamark** [comment]
BTW this jar gs-web-elasticsearch--geoserver.jar for some reason is not being produced at build (mvn insall) time (for me) even though the shade plugin is set up to build it. I'm looking into that one.

**Comment by sjudeng** [comment]
Hi,

Can you check that you built using the "deploy" profile?

mvn clean package -P deploy

This will build the shaded gs-web-elasticsearch-2.7-SNAPSHOT-geoserver.jar that you would put in your GeoServer lib directory.

**Comment by giaconiamark** [comment]
Thanks for the quick response... that worked so now it actually tries to connect in the geoserver "New vector data source" page.. but now I get this
Error creating data store, check the parameters. Error message: None of the configured nodes are available: []
Still looking into it

**Comment by sjudeng** [comment]
This error can happen if the cluster name or index name is incorrect. By the way, you mentioned that you initially copied all jars from both modules into GeoServer. This might cause some GeoServer instabilities. If possible, try to restore the original GeoServer libs to make sure you have a clean slate.

**Comment by giaconiamark** [comment]
thanks, I got all the way to the point that I now have a "layer," but I can't seem to make the layer show up in the "layer preview" inside the GeoServer web ui. Any idea why?

**Comment by giaconiamark** [comment]
@sjudeng thanks for the help, I got it working quite well. One thing I noticed is that we cannot put an indexname with a * after it as the indexname in the "new vector source" dialog. We generate a daily index of a large amount of points, and it is not feasible to configure everyone every day... Elastic allows a * on the end of a prefix in order to query across multiple indices...for instance we query  vector-* to query across all the indices that start with vector-.  I will try to take a look at the code to see if it is possible to add that functionality, because it is a common Elastic design pattern to query across many indices

**Comment by sjudeng** [comment]
Glad you've gotten further with this. Leveraging support for querying multiple indices would be a great feature to add. I think the first place to look at on this is the construction of the feature type when multiple indices are specified.
https://github.com/ngageoint/elasticgeo/blob/master/gt-elasticsearch/src/main/java/mil/nga/giat/data/elasticsearch/ElasticDataStore.java#L183-L202

**Comment by giaconiamark** [comment]
Thanks, I'll close this issue, and open another to support index name wildcarding in the store setup
