### ISSUE TITLE
support for elasticsearch 2.4.x

### ISSUE THREAD

**Issue by nreese** [ngageoint/elasticgeo#20]
Are there plans to create a release for elasticsearch 2.4?

**Comment by sjudeng** [comment]
I haven't looked at 2.4 yet but will try to take a look in the next couple weeks

**Comment by nreese** [comment]
I was able to make a jar that worked with 2.4.1 just be upgrading the
elasticsearch version in the POM

**Comment by sjudeng** [comment]
That's promising if it compiles out of the box. I'll keep the ticket open until we get it added in the next binary release.
