### ISSUE TITLE
support for Elasticsearch 5.0

### ISSUE THREAD

**Issue by nreese** [ngageoint/elasticgeo#22]

**Comment by sjudeng** [comment]
Work on this is planned but not started yet

**Comment by arosenheinrich** [comment]
+1

**Comment by dersteppenwolf** [comment]
+1

**Comment by spreeker** [comment]
+ :100:

**Comment by sjudeng** [comment]
Done. Please open a new PR if you have any issues running under Elasticsearch 5. Tested with 5.1.1 and 5.1.2.

https://github.com/ngageoint/elasticgeo/releases/tag/2.10.1-RC1

**Comment by dersteppenwolf** [comment]
Perfect!
