### ISSUE TITLE
Use geohash_grid aggregation results for tile generation

### ISSUE THREAD

**Issue by nreese** [ngageoint/elasticgeo#24]
Would it be possible to use the results of the geohash_grid aggregation for tile generation instead of query results?

**Comment by sjudeng** [comment]
FYI there's some initial work on this in the [geohashgrid branch](https://github.com/ngageoint/elasticgeo/tree/geohashgrid) (see [aggregation documentation](https://github.com/ngageoint/elasticgeo/blob/geohashgrid/gs-web-elasticsearch/doc/index.rst#aggregations)). Will merge into master and create a release in the coming days.

**Comment by sjudeng** [comment]
Release candidate including Geohash grid aggregation support is [available here](https://github.com/ngageoint/elasticgeo/releases/tag/2.10.2-RC1).
