### ISSUE TITLE
viewparams - provide query and aggregation

### ISSUE THREAD

**Issue by nreese** [ngageoint/elasticgeo#28]
Is it possible to provide both a query and aggregation in viewparams? If so, what is the syntax?

**Comment by sjudeng** [comment]
Yes, use a semi-colon as separator: `viewparams=q:encoded_query_body;a:encoded_aggregation_body`. See [SQL Views documentation](http://docs.geoserver.org/stable/en/user/data/database/sqlview.html#using-a-parametric-sql-view) for more info. I need to update docs to include this.

**Comment by nreese** [comment]
Thanks. I have a kibana [tilemap plugin](https://github.com/nreese/enhanced_tilemap) that allows for putting WMS overlays on the map. And...if the WMS layer is served from Elasticsearch with ElasticGeo, it passes kibana's filter context to the WMS layer. Meaning that the WMS layer updates anytime new kibana filters are applied. I can even use WMS layers generated from aggregations now!

![animated_wms_agg](https://cloud.githubusercontent.com/assets/373691/24522013/655eff98-154b-11e7-890c-dcbe10662d86.gif)

**Comment by sjudeng** [comment]
Sounds powerful. Thanks for sharing.
