### ISSUE TITLE
wmts support

### ISSUE THREAD

**Issue by tomerorenstein** [ngageoint/elasticgeo#29]
hey :)

I have tried using WMTS instead of WMS with this plugin and got semi success.

The problems are:
1. when not using viewparams option in url - the data returns back ok beside of some areas that the tile doesnt return(works with WMS).
2. when trying using viewparams to add query in url - it is not working and im getting all data back instead of only the queried features. (works in WMS) 

Thanx alot!

**Comment by sjudeng** [comment]
What client(s) are you using for WMTS? If relevant can you post some example layer configs/connection parameters?
