### ISSUE TITLE
Error creating data store (ES 5.3.0 & GeoServer 2.10.0)

### ISSUE THREAD

**Issue by puecher** [ngageoint/elasticgeo#32]
Hi,

I get the following error (ES 5.3.0, GeoServer 2.10.0, guava-21.0.jar):

Error creating data store, check the parameters. Error message: None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{127.0.0.1:9200}]

Settings:

index_name = my_es_index
search_indices = (empty)
cluster_name = elasticsearch (http://localhost:9200/_nodes... "cluster_name")

**Comment by sjudeng** [comment]
Hi,

Can you confirm the plugin was compiled for ES 5.3.0 (or other 5.x version)? The error shows it's trying to connect to the ES HTTP port (9200) using the transport client. You could try changing the port to 9300 but I'd like to understand why it's not using the HTTP/REST client.

**Comment by puecher** [comment]
Hi, thank you for the info. I was using your pre-compiled 2.10.2-RC2-es2.4.4 binary version, I thought  your latest version is only for es 5.X. Sorry about that, now using elasticgeo2.10.2-gs2.10.2-es5.1.2 it works! ;)

**Comment by sjudeng** [comment]
Great, glad you're up and running.
