### ISSUE TITLE
How do you configure logging?

### ISSUE THREAD

**Issue by nreese** [ngageoint/elasticgeo#35]
Can you please provide an example of configuring the logging to display all elasticsearch requests and responses.

**Comment by sjudeng** [comment]
Add the below two lines to the GeoServer logging configuration file.

```
log4j.category.mil.nga.giat.data.elasticsearch=DEBUG
log4j.category.mil.nga.giat.process.elasticsearch=DEBUG
```

The logging configuration file will be in the `logs` subdirectory in the GeoServer data directory. Check GeoServer global settings for which file is being used (e.g. `DEFAULT_LOGGING.properties`, etc.).

![elasticsearch_logging](https://cloud.githubusercontent.com/assets/11000076/25248666/b046bd5e-25d4-11e7-9467-60a8b1b42efc.png)

The plugin does [log requests](https://github.com/ngageoint/elasticgeo/blob/956483a5f5246c50471b2b109ad1cd974fee8374/gt-elasticsearch-parent/gt-elasticsearch-core/src/main/java/mil/nga/giat/data/elasticsearch/RestElasticClient.java#L118) but does not currently log responses unless there's an error. You could also try adding something like `log4j.logger.org.elasticsearch=DEBUG` or `log4j.logger.org.apache.commons.httpclient=DEBUG` to get more detailed logging. I haven't tried that before though.

Let me know if this doesn't work. Either way please keep this issue open as the documentation [here](https://github.com/ngageoint/elasticgeo/blob/master/gs-web-elasticsearch/doc/index.rst#configuring-logging) should be updated with this information.
