### ISSUE TITLE
array splitter

### ISSUE THREAD

**Issue by tomerorenstein** [ngageoint/elasticgeo#41]
hey :)

while im using this amaizing plugin, i notice that when i want to get field in my elastic type which is array, there is a logic which gives the array values seperated by semi colon.

This is a problem because when my data has semi colon itself i cannot use split by semi colon.(my data is dynamic).
Can i control somehow on the splitter?

Thanx alot!

**Comment by sjudeng** [comment]
Unfortunately the delimiter is not configurable without modifying the code at this point. The relevant line in the code is [here](https://github.com/ngageoint/elasticgeo/blob/eb864ca91e5f37b1bdfcfe1b4b3c544c8ef1fac7/gt-elasticsearch/src/main/java/mil/nga/giat/data/elasticsearch/ElasticFeatureReader.java#L154). Maybe this can be addressed at the same time as #37, which involves the same area of the code, either by exposing the delimiter as a store parameter or something else.

**Comment by sjudeng** [comment]
@tomerorenstein There are some updates to improve array handling in #42. Please take a look if you're able.

**Comment by sjudeng** [comment]
This update has been incorporate in the [2.11.1-RC1](https://github.com/ngageoint/elasticgeo/releases/tag/2.11.1-RC1) release candidate.
