### ISSUE TITLE
Maven Compile Error

### ISSUE THREAD

**Issue by miramiii** [ngageoint/elasticgeo#44]
Hi, I've managed to successfully installed in GeoServer and while building with Maven, I encounter a problem when I tried to run mvn verify, integration tests with Elasticsearch.

[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.18.1:start (docker-start) on project gt-elasticsearch: I/O Error: Unable to start container id [8e1a94ca45c0]: driver failed programming external connectivity on endpoint happy_brahmagupta (131a537b12a272664fb1ed63abf77b7a5d446314b9d9b816e2c715f28a1fbcbe): Error starting userland proxy: listen tcp 0.0.0.0:9200: bind: address already in use (Internal Server Error: 500)

Is it possible the error is due to the ipadress and port of Elasticsearch instance? If it is different from localhost, which configuration files should I change?

**Comment by sjudeng** [comment]
Hi, Do you already have a local Elasticsearch instance running on port 9200? You can either stop that instance when running the integration tests or run tests with `docker.skip`.

```bash
mvn verify -Ddocker.skip=true
```
