### ISSUE TITLE
elasticgeo doesn't support Elasticsearch index aliases

### ISSUE THREAD

**Issue by climbingsavage** [ngageoint/elasticgeo#45]
Using Geoserver 2.9.1 and Elasticsearch 2.4.1
Attempting to create a new store using an Elasticsearch index alias name. Geoserver successfully allows the creation of the store, but no layers are presented in the "Publish" screen. Works as expected when the actual index name is used. However, this precludes the ability to publish time-based indexes that are aliased to a single name, i.e. Elasticsearch indexes named "data_week_1", "data_week_2", "data_week_3" are aliased to "data"

**Comment by sjudeng** [comment]
As a workaround try using the `search_indices` store parameter. Use one of the indices (e.g. "data_week_1") for `index_name` and the pattern (e.g. "data_week*") for the `search_indices` parameter.

**Comment by sjudeng** [comment]
Added support for index aliases (see [2.11.2-RC1](https://github.com/ngageoint/elasticgeo/releases/tag/2.11.2-RC1) release) so the above workaround shouldn't be necessary. Just use your alias ("data_week") for the index name.

**Comment by sjudeng** [comment]
This should be resolved now as described above. Please reopen if there's still an issue.
