### ISSUE TITLE
Getting started and vector tiles

### ISSUE THREAD

**Issue by westover** [ngageoint/elasticgeo#50]
I am trying to get started with this plugin and trying to understand its configuration. We have some time dependent spatial data which is being stored in elastic search. I have a specific doctype for these objects. This ends up meaning that the data is split across different indices. Do I specify a specific index and then a regex for the search indices?

**Comment by sjudeng** [comment]
If you're using index aliases you can use the alias for the index name. With the support for index aliases (added in #47) the `search_indices` parameter can maybe be removed. But your description is how it would be used if you're not using index aliases ... the `index_name` would be one of the indices (e.g. `the_index_2017`) so the plugin can read the schema and the `search_indices` would be the relevant [multi-index](https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-index.html) expression (e.g. `the_index*`).

**Comment by westover** [comment]
Do you have a place where I can look to see what a typical query would look like when a TMS request is made through GWC?

**Comment by sjudeng** [comment]
You can turn up logging to see the Elasticsearch queries being executed for your requests. See https://github.com/ngageoint/elasticgeo/blob/master/gs-web-elasticsearch/doc/index.rst#configuring-logging.

**Comment by westover** [comment]
Are there any plans to be able to specify doctype?

**Comment by sjudeng** [comment]
The index is configured when you create the Elasticsearch data store and you choose the type when you create the layer from the store (see http://docs.geoserver.org/stable/en/user/data/webadmin/layers.html#add-a-layer).
