### ISSUE TITLE
SSL for ElasticGeo

### ISSUE THREAD

**Issue by pelangov728** [ngageoint/elasticgeo#51]
Hi,

I'm trying to incorporate this plugin for our project.  However, our project requires an https (not http) connection with a cert and a key.  Because of this, the ElasticDataStore constructor is crashing on line 102 since an http connection won't work for us: https://github.com/ngageoint/elasticgeo/blob/master/gt-elasticsearch/src/main/java/mil/nga/giat/data/elasticsearch/ElasticDataStore.java.  Is there support for https in ElasticGeo?  If so, please let me know how to input my cert, key, and https url.

Thanks.

**Comment by sjudeng** [comment]
HTTPS support is not currently implemented but we'll look at adding that in the coming weeks.

**Comment by pelangov728** [comment]
Thanks for your reply!  Please let me know once HTTPS is supported, it would be very useful for us :)

**Comment by michimau** [comment]
It would be perfect to have an option to accept self signed certificates too.

**Comment by sjudeng** [comment]
The update to add SSL support is pushed and is included in the [2.12.0-RC1](https://github.com/ngageoint/elasticgeo/releases/tag/2.12.0-RC1) release candidate. The current implementation just picks up configuration from the environment (see https://github.com/ngageoint/elasticgeo/blob/master/gs-web-elasticsearch/doc/index.rst#configuring-ssl-tls).

@michimau There's also an added `reject_unauthorized` property that can be set to false when testing with self-signed certs.
