### ISSUE TITLE
No Support for Wildcarded Indexes

### ISSUE THREAD

**Issue by finnessyj** [ngageoint/elasticgeo#58]
A great feature to be added would be the ability to wildcard indexes in elastic search. For example, if you're using time-based indexes for twitter data, and you've got twitter-2017.10, twitter-2017.11, twitter-2017.12, and twitter-2017.01, all of which have the same fields, it would be great to add a single Vector Data Source that is twitter-* (like Kibana). Elastic Search should handle that query, it would just need to be passed through and verified. Obviously, the hard part is ensuring that the fields match, and managing fields being added and removed from index to index. But...kibana can do it, and it would be fantastic if elasticgeo could do it too.

**Comment by sjudeng** [comment]
Previous versions supported a separate store configuration parameter to define wilcard indices (see `search_indices` in [2.11.2 store configuration documentation](https://github.com/ngageoint/elasticgeo/blob/2.11.2-RC1/gs-web-elasticsearch/doc/index.rst#configuring-data-store)). This was removed after the merge of #47 (support for index aliases). Would the current support for [index aliases](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html) accomodate your use case?

**Comment by finnessyj** [comment]
That looks like a good possibility. Let me try it out, and I'll report back.

**Comment by finnessyj** [comment]
Well, it worked...until tomorrow. If you have day indexes, you'll have to re-alias every day. From Elastic Search's [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html):

> In this case, the alias is a point-in-time alias that will group all current indices that match, it will not automatically update as new indices that match this pattern are added/removed.

That means, if the index isn't created at the time of the alias, it won't be included, whereas a wildcard on the query will be updated at the time of the query.

**Comment by sjudeng** [comment]
Thanks for the explanation. I'll revert the commit (https://github.com/ngageoint/elasticgeo/commit/d0660ed50ca222748443904e42892f5740af8e9a) that removed `search_indices` as part of the next release.

**Comment by sjudeng** [comment]
Instead of restoring `search_indices` I added support for wildcards in the index name. Once GeoServer 2.12.2 is released I'll publish a new plugin release with these updates. In the meantime you can build and test off master if you're interested.

**Comment by finnessyj** [comment]
Awesome! Thanks! Looking forward to it.

**Comment by sjudeng** [comment]
The [2.12.2-RC1](https://github.com/ngageoint/elasticgeo/releases/tag/2.12.2-RC1) release candidate that includes this update is now published.
