### ISSUE TITLE
Refresh a layers attributes if mapping change in Elasticsearch.

### ISSUE THREAD

**Issue by hokieg3n1us** [ngageoint/elasticgeo#61]
Currently, using ElasticGeo, it seems that whenever we create a mapping change on the index the store is referencing, we have to delete the layer and recreate it for those new fields in Elasticsearch to be recognized. It'd be nice to have even a refresh button on a layer to trigger an update to the attributes by reaching out to the mapping API.

**Comment by sjudeng** [comment]
Included in 2.13.0 release
