### ISSUE TITLE
Support for Elasticsearch circle geo_shape objects

### ISSUE THREAD

**Issue by warwickdufour** [ngageoint/elasticgeo#64]
I work in the field of visualising aviation data such as aerodromes, airspaces and airways. Recently I needed to visualise [NOTAMs](https://en.wikipedia.org/wiki/NOTAM) which, at their most basic, consist of a point and circle radius and as far as I know ElasticGeo does not support them.

I have cloned and modified ElasticGeo so that it does support them, albeit quite simplistically. If it is of interest I am happy to contribute my additions to the code base but as it has been a long time since I did so I would like some help with the whole 'pull request' process.

**Comment by sjudeng** [comment]
Sounds great. Thanks for thinking of contributing the feature. Here are some links on the PR process in general.

1. [Fork](https://guides.github.com/activities/forking/) this project
1. [Add remote](https://help.github.com/articles/adding-a-remote/) for your fork:<br/> `git remote add warwickdufour https://github.com/warwickdufour/elasticgeo.git`
1. If you haven't already create a branch for your feature: <br/> `git checkout -b circle`
1. Push your feature branch to your remote: <br/> `git push warwickdufour circle`
1. [Create pull request](https://help.github.com/articles/creating-a-pull-request/) through the GitHub UI
1. (If necessary) push updates to your branch based on pull request review feedback: <br/> `git commit ...` <br/> `git push warwickdufour circle`

**Comment by warwickdufour** [comment]
Hi @sjudeng , taken me a while to get round to it I'm afraid but I'm just about to create a pull request. I'm presuming I should 'compare across forks'  as per the attached image:
![screenshot from 2018-04-04 14-04-09](https://user-images.githubusercontent.com/6906992/38309134-160ebdcc-3811-11e8-9c36-ddabedefe8df.png)

**Comment by sjudeng** [comment]
Closed in #67
