### ISSUE TITLE
X-Pack Security support

### ISSUE THREAD

**Issue by corneversloot** [ngageoint/elasticgeo#78]
Hi there, I am considering using this Elasticsearch connector for a project as it looks like a good fit what what I need. The Elasticsearch will be secured though using X-Pack so I am wondering weather this connector sopports that. A (very) quick review of the code gives me the impression it is not supported. Is this correct, and if so do you have any plans to add it any time soon? Thanks!

**Comment by corneversloot** [comment]
It would be great if you can add it. If not, I might try to make changes later and submit a PR. Regardless of the particular project I might need it for I can see benefit of supporting X-Pack authorization to the connector. Thanks for the quick response!

**Comment by BinyaminSchein** [comment]
Why is this issue closed? How can you pass basic authentication parameters?

**Comment by sjudeng** [comment]
The new release candidate [2.14.2-RC1](https://github.com/ngageoint/elasticgeo/releases/tag/2.14.2-RC1) includes updates to support basic authentication.
