### ISSUE TITLE
ClassCastException when walking a mapping with attribute called "type"

### ISSUE THREAD

**Issue by IamJeffG** [ngageoint/elasticgeo#8]
When publishing a new layer for an index that contains the following type mapping:

	{
	  "myindexname" : {
	    "mappings" : {
	      "baz" : {
		"_all" : {
		  "enabled" : false
		},
		"_id" : {
		  "path" : "id"
		},
		"_timestamp" : {
		  "enabled" : true,
		  "store" : true
		},
		"properties" : {
		  "crs" : {
		    "dynamic" : "true",
		    "properties" : {
		      "properties" : {
		        "dynamic" : "true",
		        "properties" : {
		          "name" : {
		            "type" : "string"
		          }
		        }
		      },
		      "type" : {
		        "type" : "string"
		      }
		    }
		  },
		  "geometry" : {
		    "type" : "geo_shape",
		    "tree" : "quadtree",
		  }
		}
	      }
	    }
	  }
	}

Geoserver crashes with a stack trace, saying HashMap can't be cast as a String.

The trick is that the mapping above has `{"type": {"type": "string"}}`, and the value of the first `type` key is not a string.  This stems from [ElasticDataStore's walk method](https://github.com/ngageoint/elasticgeo/blob/master/gt-elasticsearch/src/main/java/mil/nga/giat/data/elasticsearch/ElasticDataStore.java#L258).

**Comment by sjudeng** [comment]
I committed and pushed a fix, which was especially easy thanks to the details you provided in your bug report.

**Comment by IamJeffG** [comment]
Many thanks for the quick response, @sjudeng !
