### ISSUE TITLE
how  es cluster  config  in  geoserver

### ISSUE THREAD

**Issue by lzp0070007** [ngageoint/elasticgeo#82]
i have three  es node ,   192.168.177.206:9200,192.168.177.142:9200,192.168.177.134:9200,

so  how config  in geoserver

**Comment by sjudeng** [comment]
Currently it's only supported to specify a single (host, port) pair corresponding to the master node in your cluster. We can leave this issue open to track updates to support providing multiple hosts.

**Comment by BinyaminSchein** [comment]
Does the geoserver get the rest of the nodes from the master and query all cluster nodes or query only the master itself?

**Comment by sjudeng** [comment]
Currently only the single host is included in the client configuration (see [here](https://github.com/ngageoint/elasticgeo/blob/c545bece9d36e39b1d22dd75a16a0ca86ccc7375/gt-elasticsearch/src/main/java/mil/nga/giat/data/elasticsearch/ElasticDataStoreFactory.java#L137)). But supporting multiple hosts would be a nice update.

**Comment by sjudeng** [comment]
The update to support multiple Elasticsearch hosts in the GeoServer config has been merged. See the  `elasticsearch_host` parameter examples in the [documentation](https://github.com/ngageoint/elasticgeo/blob/master/gs-web-elasticsearch/doc/index.rst#configuring-data-store). The update is included in the latest releases ([2.14.0](https://github.com/ngageoint/elasticgeo/releases/tag/2.14.0-RC1) for GeoServer 2.14.x and [2.13.3](https://github.com/ngageoint/elasticgeo/releases/tag/2.13.3) for earlier versions).
