### ISSUE TITLE
Geoserver 2.14.0

### ISSUE THREAD

**Issue by BinyaminSchein** [ngageoint/elasticgeo#83]
Would it be possible to create a release for geoserver 2.14.0?

**Comment by sjudeng** [comment]
We'll look at creating a new release in the coming weeks. Looks like there may be some breaking changes that will need to be investigated (some of the tests fail when running againt GeoServer 2.14.0/GeoTools 10.0).

**Comment by sjudeng** [comment]
A candidate release has been generated for GeoServer 2.14.0:

https://github.com/ngageoint/elasticgeo/releases/tag/2.14.0-RC1
